apiVersion: v1
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''
    [security]
    allow_embedding = true
    [auth.anonymous]
    enabled = true
    [dataproxy]
    timeout = 600
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-05-31T19:17:41Z"
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 9.5.2
    helm.sh/chart: grafana-6.56.6
  name: prometheus-grafana
  namespace: default
  resourceVersion: "1003"
  uid: e8e1b59c-ed6e-4aa7-81da-129d199dab8b
